# Generated by Django 5.2 on 2025-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='content',
            field=models.TextField(blank=True, help_text='HTML или Markdown'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='Будет частью URL', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='template_name',
            field=models.CharField(default='menu/menu_item_detail.html', help_text='Шаблон для рендеринга контента', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_named_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Если прописан явно, то будет игнорироваться slug', max_length=200),
        ),
    ]
