# Generated by Django 5.2 on 2025-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_content_menuitem_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='template_name',
            field=models.CharField(default='menu/home.html', help_text='Шаблон для рендеринга контента', max_length=200),
        ),
    ]
