# Generated by Django 5.2 on 2025-04-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_unique_together_remove_menuitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='hierarchy_path',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
